spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc_9th_?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: asdf
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
